### ISSUE TITLE
Downloading from local m3u8 files

### ISSUE THREAD

**Issue by elmateo487** [zmwangx/caterpillar#1]
Hey,

Looking to try out this implementation, but I am unable to download from a local m3u8 file that contains remote links. I don't see a way to point to a local file.

Any ideas?

The reason why I am looking for this is I am trying to remove the intro video from a remote playlists, so I save the playlist and edit it.

Thanks!

**Comment by zmwangx** [comment]
> a local m3u8 file that contains remote links

> I don't see a way to point to a local file.

Those descriptions sound pretty confusing. Please include an example.

Also, it sounds like this is just a question that has nothing to do with my project? Please use StackOverflow for that.

**Comment by elmateo487** [comment]
This has to do with your project. I see no way to use a m3u8 file locally stored on a machine, instead of stored on a server. Your software requires it to be downloaded via http, or at least it seems.

I have included a renamed to .txt, m3u8 file example.
[example.txt](https://github.com/zmwangx/caterpillar/files/2797525/example.txt)

Your software can't download from a file stored locally on your machine. Don't know how to better explain that.

**Comment by elmateo487** [comment]
Sure, I understand how to serve the file up myself. This is mostly an enhancement idea, as nearly all solutions like this, FFmpeg included, don't need m3u8 files to be served via http, they can be served locally from a file system. If this is just a merged of HLS portions, the files are downloaded from the links int the m3u8 using the params inside the m3u8. All information needed to do this is inside the m3u8 and doesn't require the m3u8 to live on a server.

**Comment by elmateo487** [comment]
Thanks,

I redacted the AES key from the example, HLS streams can be decrypted down into a video segments if you have the keys. Once decrypted the individual pieces can be stored however you like.

Anyways, thanks! Have a good one.

**Comment by zmwangx** [comment]
> HLS streams can be decrypted down into a video segments if you have the keys. 

Yeah, if you have the key then great, but my tool doesn't do decoding for you, so you need to download all the individual segments, decode them, then my code could kick in. The code you would be interested in is [merge.py](https://github.com/zmwangx/caterpillar/blob/master/src/caterpillar/merge.py), which works on strictly local playlists and segments.
