### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by Microeinstein** [zmwangx/caterpillar#5]
The global variable **`UESR`**`_CONFIG_DIR`
should be named **`USER`**`_CONFIG_DIR`

https://github.com/zmwangx/caterpillar/blob/master/src/caterpillar/utils.py#L45

**Comment by zmwangx** [comment]
Thanks, fixed in dc56c62. This doesn't impact anything user facing, but let me know if you'd like to see a new release tagged for some reason (otherwise it likely won't be tagged for a long time).
